hk: OK了
eureka:
  client:
    service-url:
      defaultZone: http://101.132.151.69:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
