server:
  port: 9000
spring:
  application:
    name: server-router-zuul
zuul:
  #所有服务都可以传递cookie(所有服务忽略敏感头)
  sensitive-headers: 
  #routes:
#    myUser:
#      path: /myUser/**
#      serviceId: service-user
  #简洁写法
    #service-user: /myUser/**
  #ignored-patterns: /**/service-user/index2
  #排除某些路由
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
management:
  security:
    enabled: false

