server:
  port: 9000
spring:
  application:
    name: server-router-zuul
  cloud:
    config:
      discovery:
        enabled: true
        service-id: server-config
      profile: pro
zuul:
  routes:
  #排除某些路由
  ignored-patterns: /**/service-user/index2
  
